---
- name: deployment 
  hosts: remoteservers
  gather_facts: false
  become: yes

  tasks:
  - name: Ping hosts
    ansible.builtin.ping:

  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes

  - name: Creates directory
    file:
      path: /src/ansible
      state: directory

  - name: Clone Branch 
    ansible.builtin.git:
      repo: https://github.com/joon628/menudelivery.git
      dest: /src/ansible
      single_branch: yes
      version: production

  - name: install things
    pip: name=virtualenv

  - name: create virtualenv
    command: virtualenv /src/ansible/venv
  
  - name: activate virtualenv
    command: /bin/bash /src/ansible/venv/bin/activate

  - pip: requirments=/src/ansible/requirements.txt virtualenv=/src/ansible/venv
  
  