---
- name: deployment 
  hosts: remoteservers
  gather_facts: false

  vars:
    app_name: MenuDelivery
    repo_url: https://github.com/joon628/menudelivery.git
    repo_remote: origin
    repo_version: main
    app_dir: /LSD
    virtualenv_root: /LSD/MenuDelivery

  tasks:
  - name: Ping hosts
    ansible.builtin.ping:

  - name: git pull project
    git: repo= {{repo_url}} dest={{app_dir}}/{{app_name}} version=main

    notify:
     - restart app

  - name: Install python to remote host
    raw: 'cat < /LSD/MenuDelivery/ansible/script.sh'
    args: 
      executable: /bin/bash

  - name: install things
    pip: name=virtualenv

  - name: create virtualenv
    command: virtualenv /LSD/MenuDelivery/venv
  
  - name: activate virtualenv
    command: /bin/bash /LSD/MenuDelivery/venv/bin/activate

  - pip: requirments=/LSD/MenuDelivery/requirements.txt virtualenv=/LSD/MenuDelivery/venv
  
  