---
- name: deployment 
  hosts: remoteservers
  gather_facts: false
  become: yes

  tasks:
  - name: Ping hosts
    ansible.builtin.ping:

  - name: git pull project
    git:
      repo: https://github.com/joon628/menudelivery.git
      dest: /src/ansible/
      update: yes
      version: main

  